### PR TITLE
Adding migrations bits

### PR DESCRIPTION
**Pull request by dexhorthy**

### CODE REVIEW

**Comment by dexhorthy** [comment]
goes with github.com/replicatedhq/kots.io/pull/209

**Comment by austinchambers** [comment]
How is this supposed to work? I feel like we need a README.md or something to describe how to use this migrations approach.

**Comment by dexhorthy** [comment]
@austinchambers how about a readme with a link to the guide?

**Comment by dexhorthy** [comment]
@austinchambers if that's the only blocker, how about we merge this so I can merge the guide, and then i'll come back and add a link

**Review by austinchambers — APPROVED** [review]

**Pull request merged**
